# Generated by Django 5.0.4 on 2024-04-06 08:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tree_menu_app", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="menuitem",
            name="menu",
        ),
        migrations.RemoveField(
            model_name="menuitem",
            name="named_url",
        ),
        migrations.RemoveField(
            model_name="menuitem",
            name="parent",
        ),
        migrations.RemoveField(
            model_name="menuitem",
            name="url",
        ),
        migrations.AddField(
            model_name="menuitem",
            name="link",
            field=models.CharField(default="/", max_length=200),
        ),
        migrations.AlterField(
            model_name="menuitem",
            name="title",
            field=models.CharField(default="home", max_length=100),
        ),
        migrations.DeleteModel(
            name="Menu",
        ),
    ]
